openapi: 3.0.3
info:
  title: Quiz Randomization API
  description: API endpoints for quiz randomization feature (Feature 005)
  version: 1.0.0

servers:
  - url: /api
    description: Next.js API routes

paths:
  /lessons/{lessonId}/quiz-attempts:
    post:
      summary: Create a new quiz attempt with randomization
      description: |
        Creates a new quiz attempt for the specified lesson.
        Applies randomization based on lesson settings:
        - Selects questionsToShow random questions from pool
        - Shuffles question order if shuffleQuestions is enabled
        - Shuffles answer options if shuffleAnswers is enabled
        - Persists the randomization mapping for scoring
      operationId: createQuizAttempt
      tags:
        - Quiz Attempts
      parameters:
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The lesson UUID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                seed:
                  type: string
                  description: Optional seed for reproducible randomization (testing only)
      responses:
        '201':
          description: Quiz attempt created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizAttemptResponse'
        '401':
          description: Unauthorized - user not authenticated
        '403':
          description: Forbidden - lesson not accessible to user
        '404':
          description: Lesson not found
        '409':
          description: Conflict - user already has an in-progress attempt

  /quiz-attempts/{attemptId}:
    get:
      summary: Get quiz attempt state
      description: |
        Retrieves the current state of a quiz attempt.
        Used for resuming an in-progress attempt.
        Returns questions with their randomized order and choice mappings.
      operationId: getQuizAttempt
      tags:
        - Quiz Attempts
      parameters:
        - name: attemptId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The attempt UUID
      responses:
        '200':
          description: Quiz attempt state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizAttemptResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - attempt belongs to another user
        '404':
          description: Attempt not found

  /quiz-attempts/{attemptId}/answers:
    post:
      summary: Submit an answer for a question
      description: |
        Records the user's answer for a specific question in the attempt.
        Can be called multiple times for the same question (updates previous answer).
        Validates that the question belongs to this attempt.
      operationId: submitAnswer
      tags:
        - Quiz Attempts
      parameters:
        - name: attemptId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerRequest'
      responses:
        '200':
          description: Answer recorded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerResponse'
        '400':
          description: Invalid request (missing fields, invalid questionId)
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - attempt belongs to another user
        '404':
          description: Attempt not found
        '409':
          description: Conflict - attempt already submitted

  /quiz-attempts/{attemptId}/submit:
    post:
      summary: Finalize and score the quiz attempt
      description: |
        Marks the attempt as submitted, calculates the final score,
        and determines if the user passed based on the quiz threshold.
        Cannot be called on already-submitted attempts.
      operationId: submitQuizAttempt
      tags:
        - Quiz Attempts
      parameters:
        - name: attemptId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quiz submitted and scored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizResultResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - attempt belongs to another user
        '404':
          description: Attempt not found
        '409':
          description: Conflict - attempt already submitted

  /admin/modules/{moduleId}/lesson:
    put:
      summary: Update lesson content and settings
      description: |
        Updates the lesson content including quiz randomization settings.
        Existing endpoint extended to support new fields.
      operationId: updateLesson
      tags:
        - Admin
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LessonUpdateRequest'
      responses:
        '200':
          description: Lesson updated successfully
        '400':
          description: Invalid request
        '401':
          description: Unauthorized - admin not authenticated
        '404':
          description: Module not found

components:
  schemas:
    QuizAttemptResponse:
      type: object
      required:
        - id
        - lessonId
        - status
        - questions
        - startedAt
      properties:
        id:
          type: string
          format: uuid
          description: Attempt UUID
        lessonId:
          type: string
          format: uuid
        status:
          type: string
          enum: [IN_PROGRESS, SUBMITTED, ABANDONED]
        startedAt:
          type: string
          format: date-time
        submittedAt:
          type: string
          format: date-time
          nullable: true
        score:
          type: integer
          nullable: true
          minimum: 0
          maximum: 100
        passed:
          type: boolean
          nullable: true
        questions:
          type: array
          items:
            $ref: '#/components/schemas/AttemptQuestion'
        config:
          $ref: '#/components/schemas/AttemptConfig'

    AttemptQuestion:
      type: object
      required:
        - questionId
        - position
        - questionText
        - questionType
      properties:
        questionId:
          type: string
          format: uuid
          description: Stable question UUID
        position:
          type: integer
          minimum: 1
          description: 1-indexed display position
        questionText:
          type: string
        questionType:
          type: string
          enum: [SINGLE_CHOICE, MULTIPLE_CHOICE, SHORT_TEXT]
        choices:
          type: array
          items:
            $ref: '#/components/schemas/DisplayChoice'
          description: Randomized choices for MCQ questions
        userAnswer:
          description: User's current answer (if any)
          oneOf:
            - type: string
              description: Selected label (A/B/C/D) for SINGLE_CHOICE or text for SHORT_TEXT
            - type: array
              items:
                type: string
              description: Selected labels for MULTIPLE_CHOICE
          nullable: true
        isCorrect:
          type: boolean
          nullable: true
          description: Only populated after submission
        feedback:
          type: string
          nullable: true
          description: Question feedback (only after submission)
        linkedTheorySection:
          type: string
          nullable: true

    DisplayChoice:
      type: object
      required:
        - label
        - text
      properties:
        label:
          type: string
          enum: [A, B, C, D, E, F]
          description: Display label (randomized position)
        text:
          type: string
          description: Choice text
        optionId:
          type: string
          format: uuid
          description: Stable option UUID (hidden from user, used for validation)

    AttemptConfig:
      type: object
      properties:
        questionsToShow:
          type: integer
          nullable: true
        shuffleQuestions:
          type: boolean
        shuffleAnswers:
          type: boolean
        threshold:
          type: integer
          description: Quiz pass threshold percentage

    AnswerRequest:
      type: object
      required:
        - questionId
      properties:
        questionId:
          type: string
          format: uuid
          description: The question UUID being answered
        selectedLabel:
          type: string
          description: Selected label (A/B/C/D) for SINGLE_CHOICE
        selectedLabels:
          type: array
          items:
            type: string
          description: Selected labels for MULTIPLE_CHOICE
        textAnswer:
          type: string
          description: Text answer for SHORT_TEXT questions

    AnswerResponse:
      type: object
      properties:
        questionId:
          type: string
          format: uuid
        recorded:
          type: boolean
        answeredAt:
          type: string
          format: date-time

    QuizResultResponse:
      type: object
      required:
        - attemptId
        - score
        - passed
        - totalQuestions
        - correctCount
      properties:
        attemptId:
          type: string
          format: uuid
        score:
          type: integer
          minimum: 0
          maximum: 100
        passed:
          type: boolean
        totalQuestions:
          type: integer
        correctCount:
          type: integer
        threshold:
          type: integer
        questions:
          type: array
          items:
            $ref: '#/components/schemas/QuestionResult'

    QuestionResult:
      type: object
      properties:
        questionId:
          type: string
          format: uuid
        position:
          type: integer
        isCorrect:
          type: boolean
        userAnswer:
          description: What the user answered
        correctAnswer:
          description: The correct answer (labels for review)
        feedback:
          type: string
          nullable: true
        linkedTheorySection:
          type: string
          nullable: true

    LessonUpdateRequest:
      type: object
      properties:
        theoryContent:
          type: string
        quizThreshold:
          type: integer
          minimum: 0
          maximum: 100
        practiceType:
          type: string
          enum: [IN_GAME, EXERCICES, PROJET, AUTO_EVALUATION]
        practiceInstructions:
          type: string
        practiceTimerDuration:
          type: integer
          minimum: 60
        questions:
          type: array
          items:
            $ref: '#/components/schemas/QuestionInput'
        # NEW: Randomization settings
        questionsToShow:
          type: integer
          nullable: true
          minimum: 1
          description: Number of questions to display (null = all)
        shuffleQuestions:
          type: boolean
          default: true
          description: Whether to randomize question order
        shuffleAnswers:
          type: boolean
          default: true
          description: Whether to randomize answer options

    QuestionInput:
      type: object
      required:
        - questionText
        - questionType
      properties:
        id:
          type: string
          format: uuid
          description: Existing question ID (for updates)
        questionText:
          type: string
        questionType:
          type: string
          enum: [SINGLE_CHOICE, MULTIPLE_CHOICE, SHORT_TEXT]
        options:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              text:
                type: string
        correctAnswer:
          description: Option ID(s) for correct answer
        feedback:
          type: string
        linkedTheorySection:
          type: string
        order:
          type: integer
